Lesson 04
erovneiko/thinknetica-testguru pull request #3
Opened 2020-09-07 14:41 UTC by erovneiko

2020-09-07 18:49 UTC, BubuntuClu requested changes

2020-09-07 18:49 UTC, BubuntuClu commented on app/models/user.rb
> +    .joins('JOIN users ON users.id = user_tests.user_id')
этот join лишний. ты же ("user_tests.user_id = ?", id) тут фильтруешь таблицу user_tests а не таблицу users

2020-09-07 18:49 UTC, BubuntuClu commented on db/seeds.rb
> +  { title: 'Java - Основы', level: '1', category_id: '1' },
1 - почему тут category_id как строки? это же int значения
2 - нельзя хардкодить id. в разных БД разная работа с последовательностью в таблицах. надо через объекты тут сделать. создал категории, засунь их в массив. потом при создании тестов будешь из массива категорий брать объекты и у объекта получать id. так ты гарантируешь себе правильные данные при создании
+ руби ООП язык, надо работать с объектами)

так надо сделать со всеми тестовыми данными

2020-09-08 06:00 UTC, erovneiko commented on app/models/user.rb
> +    .joins('JOIN users ON users.id = user_tests.user_id')
А... да-да, это с отладки осталось, я там ещё user.name выводил.

2020-09-10 08:00 UTC, merged