lesson_07
erovneiko/thinknetica-testguru pull request #6
Opened 2020-09-22 13:01 UTC by erovneiko

2020-09-22 18:59 UTC, BubuntuClu requested changes

2020-09-22 18:59 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(text: params[:question][:text], test_id: params[:test_id])
1 - создаем вопросы через ассоциацию теста
2 - параметры могут быть невалидные, тогда вопрос не будет создан. надо это обработать и уведомить пользователя нужным сообщением
3 - для создания объектов надо использовать strong-params

2020-09-22 18:59 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question.answers.build(text: 'dummy')
билдить тут ответы не надо, для этого будет отдельный контроллер

2020-09-22 18:59 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
попробуй опцию shallow: true

2020-09-24 13:42 UTC, BubuntuClu requested changes

2020-09-24 13:42 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test.questions.create!(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать, тогда твой бэнг-метод выкинет эксепшен, а ты его тутт не ловишь.
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2020-09-24 13:42 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    if !params[:test_id].nil?
этот код дублируется, как минимум надо вынести в метод отдельный.
если не нашелся такой объект, то не надо какие-то лишние махинации делать, у тебя отработать должен rescue_with_question_not_found, так как такой вопрос не был найден. написал метод, а потом сам делаешь так чтобы он не вызывался)

2020-09-24 13:42 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id]) unless params[:test_id].nil?
не надо проверку делать. если тест не будет найден, у тебя упадет в другом месте когда к нему будут обращения. тут должен отработать not_found метод

2020-09-24 13:42 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions, except: %i[edit update]
у тебя это один ресурс, не надо разбивать. `resources :questions, shallow: true`

2020-09-24 13:46 UTC, erovneiko commented on app/controllers/questions_controller.rb
> +    @test.questions.create!(question_params)
Дык тут же исключение ActiveRecord::RecordInvalid ловится

2020-09-24 14:06 UTC, erovneiko commented on app/controllers/questions_controller.rb
> +    if !params[:test_id].nil?
Дело в том, что этот метод у меня используется одновременно для двух случаев, и как член коллекции вопросов по порядковому номеру внутри теста и просто как объект по идентификатору из базы. params[:test_id] = nil это не исключительная ситуация, а флаг-разделитель этих двух случаев.

2020-09-24 14:08 UTC, erovneiko commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id]) unless params[:test_id].nil?
Если эту проверку не ставить, то на таких адресах "http://localhost:3000/questions/nnn" выпадает исключение "тест не найден", а в моих методах это нормальная ситуация и её нужно обработать.

2020-09-24 14:11 UTC, erovneiko commented on config/routes.rb
> +    resources :questions, except: %i[edit update]
Это понадобилось, чтобы вот эти пути вели в один и тот же экшн:
![2020-09-24_170953](https://user-images.githubusercontent.com/67379849/94156609-f0f7cb00-fe88-11ea-9514-fbf6c185cc68.png)

2020-09-24 15:10 UTC, BubuntuClu requested changes

2020-09-24 15:10 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id]) unless params[:test_id].nil?
если вводят кривой id это проблема тех кто вводит, с таким id теста нет. а ты начинаешь им что-то отдавать, зачем?

2020-09-24 15:10 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test.questions.create!(question_params)
должно не исключение выбрасываться, а рендерится страница создания с ошибками валидации чтобы пользователь мог исправить ошибки. это чуть дальше по курсу будет

2020-09-24 18:44 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions, except: %i[edit update]
это дублирование экшенов. если ты делаешь shallow: true, у тебя часть путей меняет роут, там где есть идентификатор вопроса. это сделано специально чтобы уменьшить путь в адресной строке

2020-09-24 18:45 UTC, BubuntuClu approved these changes

2020-09-24 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    if @test.questions.new(question_params).save
тебе тут потребуется объект вопроса, чтобы его вернуть на страницу, если в нем будет ошибки валидации

2020-10-05 07:38 UTC, merged