lesson_08
erovneiko/thinknetica-testguru pull request #7
Opened 2020-10-06 16:17 UTC by erovneiko

2020-10-06 18:48 UTC, BubuntuClu requested changes

2020-10-06 18:48 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test_by_question, only: %i[show edit update destroy]
для чего это требуется?

2020-10-06 18:48 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test_by_question, only: %i[show edit update destroy]
на мой взгляд это лишнее действие, ты можешь вместо @test писать @question.test. колбэки это плохая практика, надо их число стараться минимализировать

2020-10-06 18:48 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[show]
ради одного экшена не надо делать колбэк. колбэк один из способов DRY. тут тебе нечего "очищать". и вместо одной строки, тебе пришлось написать 5. ну и самого show метода тут нет

2020-10-06 18:48 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
возвращай тут сразу link_to хэлпер

2020-10-06 18:48 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(type, test)
передавай сюда объект вопроса. на основе его состояния определяй какой заголовок брать. `new_record?/persisted?`

2020-10-06 18:48 UTC, BubuntuClu commented on app/models/question.rb
> +  def text_html(n)
что такое n? имя переменной ничего не говорит о том что это такое. надо искать контекст чтобы понять что это такое

2020-10-06 18:48 UTC, BubuntuClu commented on app/models/question.rb
> +  def text_html(n)
вообще код не похож на какой-то метод модели. выглядит как какой-то хэлпер или презентер

2020-10-06 18:48 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= render template: 'tests/show' %>
отступы отсутствуют. просто стена текста

2020-10-07 04:56 UTC, erovneiko commented on app/controllers/questions_controller.rb
> +  before_action :find_test_by_question, only: %i[show edit update destroy]
У меня на всех страницах выводится шапка текущего теста. Рендерится она из другого контроллера, а там нужен @test, а не @question.test.

2020-10-07 04:59 UTC, erovneiko commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[show]
Это вообще, похоже, не надо.

2020-10-07 05:28 UTC, erovneiko commented on app/views/questions/edit.html.erb
> +<%= render template: 'tests/show' %>
А где тут нужны отступы?

2020-10-07 07:11 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= render template: 'tests/show' %>
это не конкретно про этот файл, а про все твои html.erb

2020-10-07 07:11 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +<%= render @questions %>
допустим вот здесь, у тебя этот кусок обернут в тэг table, но вложенность не видно. ее отступами показывают

2020-10-07 07:16 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    header = if question.new_record?
а зачем разметку сюда выносить? не проще разметку в html написать а здесь вернуть только текст? хэш со значениями тут тоже лишний, на мой взгляд. все хорошо помещается просто текстом в if/else

2020-10-07 07:16 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    '<b>' + header.sub('&', question.test.title) + '</b><br><br>'
интерполяция строк тебе не нравится? через "#{}"

2020-10-07 07:35 UTC, merged